on: [push]

jobs:
  practice_job:
    runs-on: ubuntu-20.04
    name: A practice job
    steps:
      - uses: actions/checkout@v2
      - name: Source Ref
        id: source_ref
        run: |
          echo "::set-output name=source_ref::$(./.github/scripts/source-ref.sh)"
        shell: bash
      - name: Print source ref
        run: echo ${{ steps.source_ref.outputs.source_ref }}
        shell: bash
      - name: Print source ref
        run: echo "$SOURCE_REF"
        shell: bash
