on: [push]

jobs:
  practice_job:
    runs-on: ubuntu-20.04
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Get dir
        run: |
          echo "::set-output name=getdir::$(./.github/scripts/getdir.sh)\n"
        shell: bash
      - name: Print dir
        run: echo ${{steps.get_dir.outputs.*}}
        shell: bash
